# Generated by Django 4.2.6 on 2024-02-24 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0010_alter_attendance_id_alter_customer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanic",
            name="user",
        ),
        migrations.RemoveField(
            model_name="request",
            name="mechanic",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Mechanic",
        ),
    ]
